routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::auth();
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {

    /**
     * Main
     */
    Route::get('/', 'PagesController@dashboard');
    Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');

    /**
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/data', 'UsersController@anyData')->name('users.data');
        Route::get('/taskdata/{id}', 'UsersController@taskData')->name('users.taskdata');
        Route::get('/leaddata/{id}', 'UsersController@leadData')->name('users.leaddata');
        Route::get('/clientdata/{id}', 'UsersController@clientData')->name('users.clientdata');
        Route::get('/users', 'UsersController@users')->name('users.users');
        Route::get('/calendar-users', 'UsersController@calendarUsers')->name('users.calendar');
    });
    Route::resource('users', 'UsersController');

    /**
    * Roles
    */

    Route::group(['prefix' => 'roles'], function () {
        Route::get('/data', 'RolesController@indexData')->name('roles.data');
        Route::patch('/update/{external_id}', 'RolesController@update');
    });
    Route::resource('roles', 'RolesController', ['except' => [
            'update'
        ]]);
    /**
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::get('/taskdata/{external_id}', 'ClientsController@taskDataTable')->name('clients.taskDataTable');
        Route::get('/projectdata/{external_id}', 'ClientsController@projectDataTable')->name('clients.projectDataTable');
        Route::get('/leaddata/{external_id}', 'ClientsController@leadDataTable')->name('clients.leadDataTable');
        Route::get('/invoicedata/{external_id}', 'ClientsController@invoiceDataTable')->name('clients.invoiceDataTable');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{external_id}', 'DocumentsController@upload')->name('document.upload');
        Route::patch('/updateassign/{external_id}', 'ClientsController@updateAssign');
        Route::post('/updateassign/{external_id}', 'ClientsController@updateAssign');
    });
    Route::resource('clients', 'ClientsController');
    Route::get('document/{external_id}', 'DocumentsController@view')->name('document.view');
    Route::get('document/download/{external_id}', 'DocumentsController@download')->name('document.download');
    Route::resource('documents', 'DocumentsController');


    /**
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::patch('/updatestatus/{external_id}', 'TasksController@updateStatus')->name('task.update.status');
        Route::patch('/updateassign/{external_id}', 'TasksController@updateAssign')->name('task.update.assignee');
        Route::post('/updatestatus/{external_id}', 'TasksController@updateStatus');
        Route::post('/updateassign/{external_id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{external_id}', 'TasksController@updateTime')->name('task.update.time');
        Route::post('/invoice/{external_id}', 'TasksController@invoice')->name('task.invoice');
        Route::patch('/update-deadline/{external_id}', 'TasksController@updateDeadline')->name('task.update.deadline');
        Route::get('/create/{client_external_id}', 'TasksController@create')->name('client.task.create');
        Route::get('/create/{client_external_id}/{project_external_id}', 'TasksController@create')->name('client.project.task.create');
        Route::post('/updateproject/{external_id}', 'TasksController@updateProject')->name('tasks.update.project');
    });
    Route::resource('tasks', 'TasksController');

    /**
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@unqualifiedLeads')->name('leads.data');
        Route::get('/unqualified', 'LeadsController@unqualified')->name('leads.unqualified');
        Route::patch('/updateassign/{external_id}', 'LeadsController@updateAssign')->name('lead.update.assignee');
        Route::patch('/updatestatus/{external_id}', 'LeadsController@updateStatus')->name('lead.update.status');
        Route::patch('/updatefollowup/{external_id}', 'LeadsController@updateFollowup')->name('lead.followup');
        Route::post('/updateassign/{external_id}', 'LeadsController@updateAssign');
        Route::post('/updatestatus/{external_id}', 'LeadsController@updateStatus');
        Route::post('/updatefollowup/{external_id}', 'LeadsController@updateFollowup')->name('lead.followup');
        Route::get('/create/{client_external_id}', 'LeadsController@create')->name('client.lead.create');

        Route::post('/covert-to-qualified/{lead}', 'LeadsController@convertToQualifiedLead')->name('lead.convert.qualified');
        Route::post('/covert-to-order/{lead}', 'LeadsController@convertToOrder')->name('lead.convert.order');
    });
    Route::resource('leads', 'LeadsController');
    Route::post('/comments/{type}/{external_id}', 'CommentController@store')->name('comments.create');

    /**
     * Projects
     */
    Route::group(['prefix' => 'projects'], function () {
        Route::get('/data', 'ProjectsController@indexData')->name('projects.index.data');
        Route::patch('/updatestatus/{external_id}', 'ProjectsController@updateStatus')->name('project.update.status');
        Route::patch('/updateassign/{external_id}', 'ProjectsController@updateAssign')->name('project.update.assignee');
        Route::post('/updatestatus/{external_id}', 'ProjectsController@updateStatus');
        Route::post('/updateassign/{external_id}', 'ProjectsController@updateAssign');
        Route::patch('/update-deadline/{external_id}', 'ProjectsController@updateDeadline')->name('project.update.deadline');
        Route::get('/create/{client_external_id}', 'ProjectsController@create')->name('project.client.create');
    });
    Route::resource('projects', 'ProjectsController');
    /**
     * Settings
     */
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'SettingsController@index')->name('settings.index');
        Route::patch('/overall', 'SettingsController@updateOverall')->name('settings.update');
        Route::post('/first-steps', 'SettingsController@updateFirstStep')->name('settings.update.first_step');
        Route::get('/business-hours', 'SettingsController@businessHours')->name('settings.business_hours');
        Route::get('/date-formats', 'SettingsController@dateFormats')->name('settings.date_formats');
    });

    /**
     * Departments
     */
    Route::group(['prefix' => 'departments'], function () {
        Route::get('/indexData', 'DepartmentsController@indexData')->name('departments.indexDataTable');
    });
    Route::resource('departments', 'DepartmentsController');

    /**
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::post('/revokeAccess', 'IntegrationsController@revokeAccess')->name('integration.revoke-access');
        Route::post('/sync/dinero', 'IntegrationsController@dineroSync')->name('sync.dinero');
    });
    Route::resource('integrations', 'IntegrationsController');

    /**
     * Notifications
     */
    Route::group(['prefix' => 'notifications'], function () {
        Route::post('/markread', 'NotificationsController@markRead')->name('notification.read');
        Route::get('/markall', 'NotificationsController@markAll');
        Route::get('/{id}', 'NotificationsController@markRead');
    });

    /**
     * Invoices
     */
    Route::get('/add-invoice-lines/{external_id}/{type}', 'InvoicesController@addInvoiceLineModalView');
    Route::group(['prefix' => 'invoices'], function () {
        Route::post('/sentinvoice/{external_id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{external_id}', 'InvoicesController@newItem')->name('invoice.new.item');
        Route::get('/{invoice}', 'InvoicesController@show')->name('invoices.show');
        Route::get('/payments-data/{invoice}', 'InvoicesController@paymentsDataTable')->name('invoice.paymentsDataTable');
    });

    /**
     * Invoice Lines
     */
    Route::delete('/invoice-lines/{invoiceLine}', 'InvoiceLinesController@destroy')->name('invoiceLine.destroy');

    /**
     * Invoices
     */
    Route::group(['prefix' => 'payment'], function () {
        Route::delete('/{payment}', 'PaymentsController@destroy')->name('payment.destroy');
        Route::post('/add-payment/{invoice}', 'PaymentsController@addPayment')->name('payment.add');
    });

    /**
     * Documents
     */
    Route::get('/add-documents/{external_id}/{type}', 'DocumentsController@uploadFilesModalView');
    Route::post('/uploaToTask/{external_id}', 'DocumentsController@uploadToTask')->name('document.task.upload');
    Route::post('/uploaToProject/{external_id}', 'DocumentsController@uploadToProject')->name('document.project.upload');
    Route::get('/search/{query}/{type?}', 'SearchController@search')->name('search');

    /**
     * Appointments
     */
    Route::group(['prefix' => 'appointments'], function () {
        Route::get('/calendar', 'AppointmentsController@calendar')->name('appointments.calendar');
        Route::get('/data', 'AppointmentsController@appointmentsJson')->name('appointments.data.json');

app/Models/Project.php
<?php

namespace App\Models;

use App\Observers\ElasticSearchObserver;
use App\Traits\DeadlineTrait;
use App\Traits\SearchableTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Services\Comment\Commentable;
use Illuminate\Database\Eloquent\Relations\MorphMany;

use Carbon\Carbon;

class Project extends model implements Commentable
{
    use  SoftDeletes, SearchableTrait, DeadlineTrait;
    const PROJECT_STATUS_CLOSED = "Closed";

    protected $searchableFields = ['title'];

    protected $fillable = [
        'title',
        'description',
        'external_id',
        'status_id',
        'user_assigned_id',
        'user_created_id',
        'client_id',
        'deadline',
    ];

    protected $dates = ['deadline'];

    public static function boot()
    {
        parent::boot();

        // This makes it easy to toggle the search feature flag
        // on and off. This is going to prove useful later on
        // when deploy the new search engine to a live app.
        //if (config('services.search.enabled')) {
        static::observe(ElasticSearchObserver::class);
        //}
    }

    public function getRouteKeyName()
    {
        return 'external_id';
    }

    public function displayValue()
    {
        return $this->title;
    }

    public function status()
    {
        return $this->belongsTo(Status::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_created_id');
    }

    public function assignee()
    {
        return $this->belongsTo(User::class, 'user_assigned_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_assigned_id');
    }

    public function documents()
    {
        return $this->morphMany(Document::class, 'source');
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function isClosed()
    {
        return $this->status->title == self::PROJECT_STATUS_CLOSED;
    }

    public function comments(): MorphMany
    {
        return $this->morphMany(Comment::class, 'source');
    }

    public function getCreateCommentEndpoint(): String
    {
        return route('comments.create', ['type' => 'project', 'external_id' => $this->external_id]);
    }

    /**
     * @return array
     */
    public function getSearchableFields(): array
    {
        return $this->searchableFields;
    }
}

resources/views/projects/_sidebar.blade.php
<div class="row">
    <div class="col-md-3">{{ __('Assigned') }}</div>
    <div class="col-md-9">
                <span id="assignee-user" class="siderbar-list-value">{{$project->assignee->name}}
                    @if(Entrust::can('can-assign-new-user-to-task'))
                        <i class="icon ion-md-create"></i>
                    @endif
                </span>

        @if(Entrust::can('can-assign-new-user-to-task'))
                <span id="assignee-picker" class="hidden">
                    <form method="POST" action="{{url('projects/updateassign', $project->external_id)}}">
                        {{csrf_field()}}
                        <select name="user_assigned_id"
                                class="small-form-control bootstrap-select assignee-selectpicker dropdown-user-selecter pull-right"
                                id="user-search-select" data-live-search="true"
                                data-style="btn btn-sm dropdown-toggle btn-light"
                                data-container="body"
                                data-dropup-auto="false"
                                onchange="this.form.submit()">
                            @foreach($users as $key => $user)
                                <option data-tokens="{{$user}}"
                                        {{$project->user_assigned_id == $key ? 'selected' : ''}} value="{{$key}}">{{$user}}
                                </option>
                            @endforeach
                        </select>
                    </form>
                </span>
        @endif

    </div>
</div>
<div class="row margin-top-10">
    <div class="col-md-3">{{ __('Created at') }}</div>
    <div class="col-md-9">
        {{ date(carbonFullDateWithText(), strtotime($project->created_at))}}
    </div>
</div>
<div class="row margin-top-10">
    <div class="col-md-3">{{ __('Deadline') }}</div>
    <div class="col-md-9">
                    <span {{Entrust::can('task-update-deadline') ? 'data-toggle=modal data-target=#ModalUpdateDeadline' : ''}}  class="siderbar-list-value {{$project->isCloseToDeadline() ? 'text-danger' : ''}}">{{date(carbonDate(), strTotime($project->deadline))}}
                        @if($project->isCloseToDeadline())
                            <span class="small text-black">({!! $project->days_until_deadline !!})</span>
                        @endif
                        @if(Entrust::can('task-update-deadline'))
                            <i class="icon ion-md-create"></i>
                        @endif
                    </span>


    </div>
</div>
<div class="row margin-top-10">
    <div class="col-md-3">{{ __('Status') }}</div>
    <div class="col-md-9">
                    <span id="status-text" class="siderbar-list-value">
                    {{ $project->status->title }}
                        @if(Entrust::can('task-update-status'))
                            <i class="icon ion-md-create"></i>
                        @endif
                    </span>
        @if(Entrust::can('task-update-status'))
                <span id="status-picker" class="hidden">
                    <form method="POST" action="{{url('projects/updatestatus', $project->external_id)}}">
                        {{csrf_field()}}
                        <select name="status_id"
                                class="small-form-control bootstrap-select status-selectpicker dropdown-user-selecter"
                                id="status-search-select"
                                data-style="btn btn-sm dropdown-toggle btn-light"
                                data-container="body"
                                onchange="this.form.submit()">
                            @foreach($statuses->pluck('title', 'id') as $key => $status)
                                <option
                                        {{$project->status->id == $key ? 'selected' : ''}} value="{{$key}}">{{$status}}</option>
                            @endforeach
                        </select>
                    </form>
                </span>
        @endif
    </div>
</div>

@push('scripts')
    <script>
        $(document).ready(function () {
            $('select').selectpicker();

            $('#assignee-user').on('click',function(){
                if($("#assignee-picker").hasClass("hidden")) {
                    $("#assignee-picker").removeClass("hidden");
                    $("#assignee-user").addClass("hidden");

                    $('.assignee-selectpicker').selectpicker('toggle')
                }
            });

            $('body').on('click',function(e){
                var container = $("#assignee-picker");

                // if the target of the click isn't the container nor a descendant of the container
                if (!container.is(e.target) && container.has(e.target).length === 0)
                {
                    if ($("#assignee-user").is(e.target)) {
                        return
                    }

                    container.addClass("hidden");
                    $("#assignee-user").removeClass("hidden");
                }

            });

            $('#status-text').on('click',function(){
                if($("#status-picker").hasClass("hidden")) {
                    $("#status-picker").removeClass("hidden");
                    $("#status-text").addClass("hidden");

                    $('.status-selectpicker').selectpicker('toggle')
                }
            });

            $('body').on('click',function(e){
                var container = $("#status-picker");

                // if the target of the click isn't the container nor a descendant of the container
                if (!container.is(e.target) && container.has(e.target).length === 0)
                {
                    if ($("#status-text").is(e.target)) {
                        return
                    }

                    container.addClass("hidden");
                    $("#status-text").removeClass("hidden");
                }

            });
        });

    </script>
@endpush

resources/views/projects/show.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
    @include('partials.clientheader')
    @include('partials.userheader', ['changeUser' => false])
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="project-board-ui">
            <nav class="navbar board text-black ">
                @if(!$project->isClosed())
                <a href="{{route('client.project.task.create', [$client->external_id, $project->external_id])}}" class="btn btn-md btn-brand" style="margin:1em;">@lang('New task')</a>
            @endif
        </nav>
            <div class="project-board-lists">
                @foreach($statuses as $status)
                <div class="project-board-list">
                    <header>{{ __($status->title)}}</header>
                    <ul class="sortable" id="{{$status->title}}" data-status-external-id="{{$status->external_id}}" style="min-height: 32em;">
                        @foreach($tasks as $task)
                        <li data-task-id="{{$task->external_id}}">
                            @if($task->status_id == $status->id)
                                <div class="project-board-card-wrapper">
                                  <div class="project-board-card">
                                    <div class="position-relative">
                                    </div>
                                    <p class="project-board-card-title"><a href="{{route('tasks.show', $task->external_id)}}" class="link-color">{{$task->title}}</a></p>
                                    <div class="project-board-card-description">{!! str_limit($task->description, 154, '...') !!}</div>
                                  </div>
                                  <div class="project-board-card-footer">
                                    <ul class="list-inline" style="padding: 8px; min-height: 3.3em;">
                                        <li class="project-board-card-list">20, February 2019</li>
                                        <li class="project-board-card-thumbnail text-right" style="float:right;">
                                        <a href="{{route('users.show', $task->user->external_id)}}" ><img src="{{$task->user->avatar}}" class="project-board-card-thumbnail-image" title="{{$task->user->name}}"/></a>
                                        </li>
                                    </ul>
                                  </div>
                                </div> 
                            @endif
                        @endforeach
                        </li>
                    </ul>
                </div>
                    @endforeach  
            </div>
        </div>
    </div>
</div>

<div class="row movedown">
    <div class="col-lg-8">
        <div class="tablet">
            <div class="tablet__body">
                <h3 class="tablet__head-title">@lang('Project completion progress')</h3>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: {{$completionPercentage}}%;" aria-valuenow="{{$completionPercentage}}" aria-valuemin="0" aria-valuemax="{{$completionPercentage}}">{{$completionPercentage}}%</div>
                </div>
            </div> 
        </div>
    </div>
    <div class="col-lg-4">
        <div class="tablet">
            <div class="tablet__body">
                <h3 class="tablet__head-title">@lang('Collaborators')</h3>
                <ul class="list-inline">
                @foreach($collaborators as $collaborator)
                <li>
                     <a href="{{route('users.show', $collaborator->external_id)}}" >
                        <img src="{{$collaborator->avatar}}" class="project-board-card-thumbnail-image" title="{{$collaborator->name}}"/>
                    </a>
                </li>
                @endforeach
                </ul>
            </div> 
        </div>
    </div>
</div>

<div class="row movedown">
      <div class="col-sm-8">
          @include('partials.comments', ['subject' => $project])
      </div>
      <div class="col-sm-4">
      <div class="tablet">
          <div class="tablet__head tablet__head__color-brand">
              <div class="tablet__head-label">
                  <h3 class="tablet__head-title text-white">@lang('Information')</h3>
              </div>
          </div>
          <div class="tablet__body">
            @include('projects._sidebar')
          </div>
      </div>
  </div>
  <div class="col-sm-4">@if(Entrust::can('project-upload-files') && $filesystem_integration)
                <div id="document" class="tab-pane">
                    <div class="tablet">
                        <div class="tablet__head">
                            <div class="tablet__head-label">
                                <h3 class="tablet__head-title">{{ __('All Files') }}</h3>
                                <button id="add-files" style="
                                margin-left: 30rem !important;
                                border: 0;
                                padding: 0;
                                background: transparent;
                                font-size:2em;">
                                    <i class="icon ion-md-add-circle text-right"></i>
                                </button>
                            </div>

                        </div>
                        <div class="tablet__body">
                            @if($files->count() == 0)
                                <div class="tablet__item">
                                    <div class="tablet__item__pic">
                                        <p class="title">@lang('No files')</p>
                                    </div>
                                </div>
                            @endif
                            <div class="tablet__items">
                                @foreach($files as $file)
                                    <div class="tablet__item">
                                        <div class="tablet__item__pic">
                                            <img src="{{url('images/doc-icon.svg')}}" alt="">
                                        </div>
                                        <div class="tablet__item__info">

                                            <a href="{{ route('document.view', $file->external_id) }}" class="tablet__item__title" target="_blank">{{$file->original_filename}}</a>
                                            <div class="tablet__item__description">
                                                {{$file->size}} MB
                                            </div>
                                        </div>
                                        <div class="tablet__item__toolbar">
                                            <div class="dropdown dropdown-inline">
                                                <button type="button" class="btn btn-clean btn-sm btn-icon btn-icon-md"
                                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="icon ion-md-more" style="font-size: 2.5em;"></i>
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="tablet__nav">
                                                        <li class="nav-item">
                                                            <a href=" {{ route('document.view', $file->external_id) }}" target="_blank" class="nav-link">
                                                                <i class="icon ion-md-eye"></i>
                                                                <span class="nav-link-text">@lang('View')</span>
                                                            </a>
                                                        </li>
                                                        <li class="nav-item">
                                                            <a href=" {{ route('document.download', $file->external_id) }}" target="_blank" class="nav-link">
                                                                <i class="icon ion-md-cloud-download"></i>
                                                                <span class="nav-link-text">@lang('Download')</span>
                                                            </a>
                                                        </li>
                                                        @if(Entrust::can('document-delete'))

                                                            <li class="nav-item">
                                            <span class="nav-link">
                                                <i class="icon ion-md-trash"></i>
                                                <form method="POST" action="{{action('DocumentsController@destroy', $file->external_id)}}">
                                                    <input type="hidden" name="_method" value="delete"/>
                                                    <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                                    <button type="submit" class="btn btn-clean nav-link-text">{{__('Delete')}}</button>
                                                </form>
                                            </span>
                                                            </li>
                                                        @endif
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                    </div>
                </div>
                @endif</div>
</div>


@if(Entrust::can('project-update-deadline'))
    <div class="modal fade" id="ModalUpdateDeadline" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">{{ __('Change deadline') }}</h4>
                </div>

                <div class="modal-body">

                    {!! Form::model($project, [
                      'method' => 'PATCH',
                      'route' => ['project.update.deadline', $project->external_id],
                      ]) !!}
                    {!! Form::label('deadline_date', __('Change deadline'), ['class' => 'control-label']) !!}
                    {!! Form::date('deadline_date', \Carbon\Carbon::now()->addDays(7), ['class' => 'form-control']) !!}
                    {!! Form::text('deadline_time', '15:00', ['class' => 'form-control', 'onkeydown' => 'return isNumberKey(this)', 'onchange' => 'validateHhMm(this)', 'id' => 'deadline_time']) !!}




                    <div class="modal-footer">
                        <button type="button" class="btn btn-default col-lg-6"
                                data-dismiss="modal">{{ __('Close') }}</button>
                        <div class="col-lg-6">
                            {!! Form::submit( __('Update deadline'), ['class' => 'btn btn-success form-control closebtn']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif
<div class="modal fade" id="add-files-modal" tabindex="-1" role="dialog" aria-hidden="true"
         style="display:none;">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$( ".sortable" ).sortable({
    axis: 'X',
    connectWith: '.sortable',
    receive: function (event, ui,) {
        var taskExternalId = ui.item.attr('data-task-id');
        var statusExternalId =  $(this).attr('data-status-external-id')
        var url = '{{ route("task.update.status", ":taskExternalId") }}';
        url = url.replace(':taskExternalId', taskExternalId);
    // POST to server using $.post or $.ajax
    $.ajax({
        data: {
            "_token": "{{ csrf_token() }}",
            "statusExternalId": statusExternalId,
            "test": $(this).parent().attr('id')
        },
        type: 'PATCH',
        url: url
    });
}
});
    @if(Entrust::can('project-upload-files') && $filesystem_integration)
    $('#add-files').on('click', function () {
        $('#add-files-modal .modal-content').load('/add-documents/{{$project->external_id}}' + '/project');
        $('#add-files-modal').modal('show');
    });
    @endif
</script>

@endpush